- name: "hello world play"
  hosts: localhost
  tasks:
  # - name: hello world to file
  #   ansible.builtin.copy:
  #     dest: "/tmp/helloworld"
  #     content: |
  #       this is my test file

  - name: install net tools
    ansible.builtin.apt:
      name:
        - net-tools
      update_cache: yes
    vars:
      ansible_become: yes